# Generated by Django 3.2 on 2024-02-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.IntegerField(default=0),
        ),
    ]
