# Generated by Django 3.2 on 2024-01-26 16:35

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reviews', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Уникальный login пользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email пользователя')),
                ('role', models.CharField(blank=True, choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', help_text='Выберете роль пользователя', max_length=9, verbose_name='Роль пользователя')),
                ('bio', models.TextField(blank=True, max_length=2000, verbose_name='Биография пользователя')),
                ('confirmation_code', models.CharField(max_length=6, verbose_name='Поле с кодом подтверждения')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.Group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_users', to='auth.Permission', verbose_name='Права пользователя')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('username', 'email'), name='uq_username_email'),
        ),
    ]
