# Generated by Django 3.2 on 2024-01-25 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('review', 'author')},
        ),
    ]
