# Generated by Django 3.2 on 2024-01-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.IntegerField(),
        ),
    ]
