# Generated by Django 3.2 on 2024-01-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_comment_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_review_author',
        ),
    ]
